""" Pre-process raw datasets.

The aim of the preprocessing stage is to keep the main pipeline (run.py) logic
clean and obvious. Dask no longer supports reading directly from feather files,
so it is cleaner to preconvert these files to parquet, which allows run.py
to load the files in a single line without worrying about memory explosions.

convert_to_parquet():
Convert proofread_connections_783.feather (the full main pipeline file) and
flywire_synapses_783.feather to parquet files.

make_tests():
Create several test datasets of varying sizes from 
proofread_connections_783.parquet for scalability testing.

"""

import os
import pyarrow
import pyarrow.feather as feather
import pyarrow.parquet as pq

from dask import dataframe as ddf

from detect_communities import get_all_nodes

CLIENT = None
ROOT_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(ROOT_DIR, "data")
METADATA_FILE = os.path.join(OUT_DIR, "test_metadata.txt")




######################## CONVERT MAIN FILES TO PARQUET #########################

def convert_one_file_to_parquet(file_to_convert, destination):
    """ Convert feather file via streaming (minimises RAM).
    NOTE: This function was originally AI generated by Copilot, but I have 
    made many modifications and added thorough annotations to improve clarity.
    """
    chunk_size = 250_000
    reader = pyarrow.ipc.open_file(file_to_convert) # Create streaming reader
    writer = None
    
    for i in range(reader.num_record_batches):
        batch = reader.get_record_batch(i) # Get subset of rows from feather file
        table = pa.Table.from_batches([batch]) # Wrap low-level batch into high-level table
        
        # Create parquet writer (once). The writer needs a schema, and that 
        # schema is supplied by the table, hence cannot do this step outside
        # the for loop.
        if writer is None:
            writer = pq.ParquetWriter(destination, table.schema)
            
        # Write batch into row groups of chunk size. Chunk size of 250,000
        # means 250,000 rows per row group/chunk. Currently do not know how
        # large the batches are in the feather file but they could be much 
        # larger than 250,000. If they are, it will dramatically slow down
        # the pipeline. 250,000 rows per chunk seems to be a healthy middle ground.
        writer.write_table(table, row_group_size = chunk_size)
        
    writer.close()
    
    
def convert_to_parquet(main_file, coord_file):
    """ Convert feather file equivalents of supplied filenames to parquet """
    global CLIENT
    
    # Get files to convert and validate their existence
    main_feather = main_file.replace(".parquet", ".feather")
    coord_feather = coord_file.replace(".parquet", ".feather")
    if not os.path.exists(main_feather) or not os.path.exists(coord_feather):
        raise FileNotFoundError("At least one of these files does not exist: \n"
                                f"{main_feather},\n{coord_feather}")
    
    # Convert files
    m = CLIENT.submit(convert_one_file_to_parquet, main_feather, main_file)
    c = CLIENT.submit(convert_one_file_to_parquet, coord_feather, coord_file)
    m.result()
    c.result()
    



#######################  MAKE SCALABILITY TEST FILES ###########################

def write_metadata(sub_connectome, test_id):
    global METADATA_FILE
    """ Write test connectome file metadata 
    E.g., number of nodes, number of edges, node:edge ratio, neuropils """
    num_nodes = get_all_nodes(
        sub_connectome, 
        node_cols=["pre_pt_root_id","post_pt_root_id"]).count().compute()
    num_edges = sub_connectome["pre_pt_root_id"].count().compute()
    node_edge_ratio = num_nodes/num_edges
    neuropils = list(sub_connectome["neuropil"].unique().compute())
    with open(METADATA_FILE, "a") as mfile:
        mfile.write(f"Testfile Metadata: {test_id}.feather\n")
        mfile.write(f"Number of nodes: {num_nodes}\n")
        mfile.write(f"Number of edges: {num_edges}\n")
        mfile.write(f"Node-edge ratio: {node_edge_ratio}\n")
        mfile.write(f"Neuropils: {neuropils}\n\n")
    

def write_subset_file(sub_connectome, test_id):
    """ Write feather file containing sub-connectome. 
    These tests should fit in memory so am using non-streaming conversion. 
    Saving as feather file to match full dataset file type. """
    global OUT_DIR
    filename = os.path.join(OUT_DIR, f"{test_id}.feather")
    pd_connectome = sub_connectome.compute()
    pd_connectome.to_feather(filename)
    
    
def make_tests(main_file):
    """ Create subsets of main file of varying sizes for performance analysis """
    # Load main parquet file
    connectome = ddf.read_parquet(main_file)
    
    # Subset dataframe into different sizes
    tiny = connectome[connectome["neuropil"].str.startswith("BU_")]
    small = connectome[connectome["neuropil"].str.startswith("LOP_")]
    medium = connectome[connectome["neuropil"].str.startswith("ME_")]    
    omit = {"ME_L", "ME_R", "LOP_L", "LOP_R"}
    large = connectome[~connectome["neuropil"].isin(omit)]
    
    # Write subset data
    subsets = [tiny, small, medium, large]
    test_ids = ["tiny", "small", "medium", "large"]
    for sub_connectome, test_id in zip(subsets, test_ids):
        write_metadata(sub_connectome, test_id)
        write_subset_file(sub_connectome, test_id)




#################################### RUN #######################################

def run(main_file, coord_file):
    global CLIENT
    CLIENT = get_client()
    convert_to_parquet(main_file, coord_file)
    make_tests(main_file)