""" Preprocess raw data 

Convert raw data from feather files to parquet files, and generate scalability 
test files of varying problem sizes.

This script should only need to be ran once.

"""
import os
import pyarrow
import pyarrow.feather as feather
import pyarrow.parquet as pq
from dask.distributed import Client
from dask.distributed import LocalCluster
from detect_communities import get_all_nodes  

CLIENT = None # Assigned at bottom of script

ROOT_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(ROOT_DIR, "data")
MAIN_FILE_RAW = os.path.join(DATA_DIR, "proofread_connections_783.feather")
COORD_FILE_RAW = os.path.join(DATA_DIR, "flywire_synapses_783.feather")
MAIN_FILE = os.path.join(DATA_DIR, "proofread_connections_783.parquet")
COORD_FILE = os.path.join(DATA_DIR, "flywire_synapses_783.parquet")




############################### PREPROCESS #####################################

def preprocess_main_file(raw_path):
    """ Convert to parquet and create scalability test files """
    global DATA_DIR, MAIN_FILE, MAIN_FILE_RAW
    test_ids = ["tiny", "small", "medium", "large"]
    test_paths = [os.path.join(DATA_DIR, f"{test_id}.parquet") 
                  for test_id in test_ids]  
    
    if not os.path.exists(MAIN_FILE):
        feather_to_parquet(file_to_convert=raw_path, destination=MAIN_FILE)
        make_tests(MAIN_FILE, test_ids, test_paths)
        
    pipeline_file_paths = test_paths + [MAIN_FILE]
    return pipeline_file_paths


def preprocess_coord_file(raw_path):
    """ Convert coordinate file to parquet file """
    global COORD_FILE
    if not os.path.exists(COORD_FILE):
        feather_to_parquet(file_to_convert=raw_path, destination=COORD_FILE)


def feather_to_parquet(file_to_convert, destination):
    """ Convert feather file via streaming (minimises RAM).
    NOTE: This function was originally AI generated by Copilot, but I have 
    made many modifications and added thorough annotations to improve clarity.
    """
    filename = os.path.basename(file_to_convert)
    print(f"\nConverting {filename} to parquet ...\n")
    chunk_size = 250_000
    reader = pyarrow.ipc.open_file(file_to_convert) # Create streaming reader
    writer = None
    
    for i in range(reader.num_record_batches):
        batch = reader.get_record_batch(i) # Get subset of rows from feather file
        table = pyarrow.Table.from_batches([batch]) # Wrap low-level batch into high-level table
        
        # Create parquet writer (once). The writer needs a schema, and that 
        # schema is supplied by the table, hence cannot do this step outside
        # the for loop.
        if writer is None:
            writer = pq.ParquetWriter(destination, table.schema)
            
        # Write batch into row groups of chunk size. Chunk size of 250,000
        # means 250,000 rows per row group/chunk. Currently do not know how
        # large the batches are in the feather file but they could be much 
        # larger than 250,000. If they are, it will dramatically slow down
        # the pipeline. 250,000 rows per chunk seems to be a healthy middle ground.
        writer.write_table(table, row_group_size = chunk_size)
        
    writer.close()
    print(f"\nConverted {filename} to parquet\n")
    

def write_test_metadata(sub_connectome, test_id):
    global METADATA_FILE
    """ Write test connectome file metadata 
    E.g., number of nodes, number of edges, node:edge ratio, neuropils """
    num_nodes = get_all_nodes(
        sub_connectome, 
        node_cols=["pre_pt_root_id","post_pt_root_id"]).count().compute()
    num_edges = sub_connectome["pre_pt_root_id"].count().compute()
    node_edge_ratio = num_nodes/num_edges
    neuropils = list(sub_connectome["neuropil"].unique().compute())
    with open(METADATA_FILE, "a") as mfile:
        mfile.write(f"Testfile Metadata: {test_id}.feather\n")
        mfile.write(f"Number of nodes: {num_nodes}\n")
        mfile.write(f"Number of edges: {num_edges}\n")
        mfile.write(f"Node-edge ratio: {node_edge_ratio}\n")
        mfile.write(f"Neuropils: {neuropils}\n\n")
    

def write_subset_file(sub_connectome, test_id):
    """ Write feather file containing sub-connectome. 
    These tests should fit in memory so am using non-streaming conversion. 
    Saving as feather file to match full dataset file type. """
    global OUT_DIR
    filename = os.path.join(OUT_DIR, f"{test_id}.parquet")
    sub_connectome.to_parquet(filename)
    
    
def make_tests(main_file, test_ids, test_paths):
    """ Create subsets of main file of varying sizes for performance analysis """
    print(f"\nGenerating test parquet files ...\n")
    connectome = ddf.read_parquet(main_file)
    
    # Subset dataframe into different sizes
    tiny = connectome[connectome["neuropil"].str.startswith("BU_")]
    small = connectome[connectome["neuropil"].str.startswith("LOP_")]
    medium = connectome[connectome["neuropil"].str.startswith("ME_")]    
    omit = {"ME_L", "ME_R", "LOP_L", "LOP_R"}
    large = connectome[~connectome["neuropil"].isin(omit)]
    
    # Write subset data 
    # TODO - could parallelise but unlikely to be a bottleneck
    subsets = [tiny, small, medium, large]
    for sub_connectome, test_id in zip(subsets, test_ids):
        write_test_metadata(sub_connectome, test_id)
        write_subset_file(sub_connectome, test_id)
    print(f"\nGenerated test parquet files\n")


################################### MAIN #######################################

def initialise_client():
    cluster = LocalCluster(
        n_workers=2,
        processes=True,
        threads_per_worker=1,
        memory_limit = "6GB",
        dashboard_address=":8787"
    )
    client = Client(cluster)
    return client


def main():
    """ Download and convert raw data """
    global MAIN_FILE_RAW, COORD_FILE_RAW
    CLIENT = initialise_client()
    file_paths_f = CLIENT.submit(preprocess_main_file, MAIN_FILE_RAW)
    coord_path_f = CLIENT.submit(preprocess_coord_file, COORD_FILE_RAW)
    file_paths = file_paths_f.result()
    coord_path = coord_path_f.result()
    print(f"\n\nPreprocessing complete!")
    

if __name__ == "__main__":
    main()